services:
  postgres:
    image: postgres:16
    container_name: expense-tracker-db
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expensedb
    ports:
      - "5433:5432"
    volumes:
      - expense_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: expense-tracker-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: expense_user
      RABBITMQ_DEFAULT_PASS: expense_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - expense_rabbitmq_data:/var/lib/rabbitmq

volumes:
  expense_pgdata:
  expense_rabbitmq_data: